Repository Dingdongrami/PicMap_frontend, pull requests merged in 2023-12, with the labels that each got.

#32 [FEAT] 지도위 클러스터링 클릭시 개별 포토 navigation 구현
  api/mapphotoApi.js
  api/photoApi.js
  api/userApi.js
  babel.config.js
  components/MapMarker/ClusteredMapView.jsx
  components/MapMarker/ClusteredMarker.jsx
  components/MapMarker/CreateIcon.jsx
  components/MapMarker/MapList.jsx
  components/MapMarker/helpers.jsx
  components/MapMarker/styles.js
  components/circle/album/AddMethod.jsx
  components/header/HeaderIcon.jsx
  components/header/Stack/AltScreen.jsx
  components/middle/Stack/AltComponent.jsx
  hooks/index.js
  hooks/useLocation.jsx
  package-lock.json
  package.json
  screens/MyPage/Map/Map.jsx
  screens/MyPage/Map/examples.js
  screens/MyPage/Post/Post.jsx
  utils/formatDate.js
  yarn.lock
Labels: bug, enhancement, feat

#39 [FEAT] 써클 속 이미지들 로컬기기로 다운로드 기능 구현
  api/downloadApi.jsx
  app.json
  components/MapMarker/MapList.jsx
  components/MapMarker/styles.js
  components/circle/single/examples.js
  package-lock.json
  package.json
  screens/MyPage/Circle/SingleCircle.jsx
  yarn.lock
Labels: feat

#45 [FIX] 사진 스와이프 버그수정
  .gitignore
  android/.gitignore
  android/app/build.gradle
  android/app/debug.keystore
  android/app/proguard-rules.pro
  android/app/src/debug/AndroidManifest.xml
  android/app/src/debug/java/com/dingdong/picmap/ReactNativeFlipper.java
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/dingdong/picmap/MainActivity.java
  android/app/src/main/java/com/dingdong/picmap/MainApplication.java
  android/app/src/main/res/drawable-hdpi/splashscreen_image.png
  android/app/src/main/res/drawable-mdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xhdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xxhdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xxxhdpi/splashscreen_image.png
  android/app/src/main/res/drawable/rn_edit_text_material.xml
  android/app/src/main/res/drawable/splashscreen.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values-night/colors.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/app/src/release/java/com/dingdong/picmap/ReactNativeFlipper.java
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
  app.json
  components/Modal/styles.js
  components/circle/album/styles.js
  package-lock.json
  package.json
  screens/MyPage/Circle/CirclePhotoCom.jsx
  screens/MyPage/Circle/MapPhotoCom.jsx
  screens/MyPage/Circle/SingleCircle.jsx
  yarn.lock
Labels: bug, feat

#46 [FIX] 로컬 기기 다운로드 중간 코드 수정완료 + 유저 검색 초기세팅
  api/friendsApi.js
  api/userApi.js
  app.json
  components/circle/single/ZoomInMap.jsx
  screens/MyPage/Circle/SingleCircle.jsx
  screens/Search/UserSearch.jsx
Labels: bug, feat

#47 [FEAT/FIX/REFACTOR] 프로필 편집, 써클 가입, 친구 기능 bugfix, 써클 유저 추가 기능
  api/circleApi.js
  components/PersonRow/PersonRow.jsx
  components/PersonRow/styles.js
  components/UserProfile/UserProfile.jsx
  components/circle/CircleRoom.jsx
  components/circle/album/Comment.jsx
  components/circle/album/PhotoComments.jsx
  components/header/CircleHeader.jsx
  components/middle/Stack/AltUserComponent.jsx
  screens/FriendsList/FriendsList.jsx
  screens/InviteUser/InviteUser.jsx
  screens/LandingPage/LandingPage.jsx
  screens/Profile/EditProfile.jsx
  screens/ReceivedFriendRequest/ReceivedFriendRequest.jsx
  screens/UserPage/Post/Post.jsx
  screens/UserPage/Post/styles.js
Labels: bug, feat
